"""remplacer lieu_naissance par pays et fuseau horaire

Revision ID: 755d4b8c5f3e
Revises: 3a6b8675a66a
Create Date: 2026-06-18 10:57:27.695585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '755d4b8c5f3e'
down_revision: Union[str, None] = '3a6b8675a66a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profils', sa.Column('pays_naissance', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('profils', sa.Column('fuseau_horaire_naissance', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.drop_column('profils', 'lieu_naissance')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profils', sa.Column('lieu_naissance', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_column('profils', 'fuseau_horaire_naissance')
    op.drop_column('profils', 'pays_naissance')
    # ### end Alembic commands ###
