"""add_claim_token_to_profils

Revision ID: bca80affefb2
Revises: 5adbe995518e
Create Date: 2026-06-25 11:25:01.001679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bca80affefb2'
down_revision: Union[str, None] = '5adbe995518e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profils', sa.Column('claim_token', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_profils_claim_token'), 'profils', ['claim_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profils_claim_token'), table_name='profils')
    op.drop_column('profils', 'claim_token')
    # ### end Alembic commands ###
